#!/bin/bash

#rsync commands to sync folders on my ubuntu machine with google drive and vice versa
#Requires a Google Drive client for ubuntu ( like OverGrive ) & run-one package

sudo rsync -a /home/raghav/Documents/ /home/raghav/Google\ Drive/Documents
sudo rsync -a /home/raghav/Music/ /home/raghav/Google\ Drive/Music    
sudo rsync -a /home/raghav/Pictures/ /home/raghav/Google\ Drive/Pictures
sudo rsync -a /home/raghav/Google\ Drive/Documents/ /home/raghav/Documents
sudo rsync -a /home/raghav/Google\ Drive/Music/ /home/raghav/Music    
sudo rsync -a /home/raghav/Google\ Drive/Pictures/ /home/raghav/Pictures
