#!/bin/bash

#This script downloads, extracts and/or formats adblocking/anti-tracking hosts file for Pi-Hole.

#Adguard
curl -s https://adguard.com/en/filter-rules.html?id=15 | sed 's/^||//' | cut -d'^' -f-1 > /var/www/html/Adguard

#Anti-Pop Ads
curl -s https://raw.githubusercontent.com/Yhonay/antipopads/master/popads.txt | sed 's/^||//' | cut -d'^' -f-1 > /var/www/html/AntiPopAds

##Airelle's Hosts

#Anti-Advertisements
curl -s http://rlwpx.free.fr/WPFF/hpub.7z > hpub.7z
7z x hpub.7z
mv -f /root/Hosts.pub /var/www/html/antiadvert
rm /root/hpub.7z

#Anti-Stalkers
curl -s http://rlwpx.free.fr/WPFF/htrc.7z > htrc.7z
7z x htrc.7z
mv -f /root/Hosts.trc /var/www/html/antistalkers
rm /root/htrc.7z

#Anti-Malacious
curl -s http://rlwpx.free.fr/WPFF/hrsk.7z > hrsk.7z
7z x hrsk.7z
mv -f /root/Hosts.rsk /var/www/html/antimal
rm /root/hrsk.7z

#Anti-Sex
curl -s http://rlwpx.free.fr/WPFF/hsex.7z > hsex.7z
7z x hsex.7z
mv -f /root/Hosts.sex /var/www/html/antisex
rm /root/hsex.7z

#EFF Cookie Blocklist
curl -s https://www.eff.org/files/cookieblocklist.txt | sed 's/^@@||//' | cut -d'^' -f-1 > /var/www/html/EFF
